name: aws-ai-demo-build-backend

on:
    push:
        branches:
              - aws
    workflow_dispatch:
jobs:
    aws-backend-build:
        runs-on: ubuntu-latest
        permissions:
          id-token: write
          contents: read

        steps:
            - uses: actions/checkout@v3
    
            - name: Print Info and Architecture
              run: |
                    echo "Working with Hash ${GITHUB_SHA}"
                    echo "Runner architecture: $(uname -m)"
                    docker version
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: ${{ secrets.AWS_GITHUB_ROLE }}
                aws-region: 'us-west-2'
            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2
            - name: Docker Build and Publish
              uses: docker/build-push-action@v5
              with:
               context: ./backend
               file: ./backend/Dockerfile
               push: true
               tags: ${{ secrets.ECR_REPO }}/llm-graph-builder-backend:${{github.run_number}}
